config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tasks
  resources :boards
  resources :users

   root 'welcome#index'
   get 'editor/:id' => 'welcome#editor', as: :editor_task

  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end

end

app/models/board.rb
class Board < ActiveRecord::Base

  belongs_to :user
  has_many :tasks 

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_ancestry

  belongs_to :board

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :boards

  private
    def self.from_omniauth(auth)
      user = where(provider: auth.provider, uid:auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid      = auth.uid
        user.email    = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name     = auth.info.name
    end

    # user.set_provider_image('facebook', auth.info.image)

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :description, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :data_init, :date_end, :order, :objetivo_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      redirect_to editor_task_url
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_task_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email, :provider, :uid)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def editor
    @Task = Task.find_by_id(params[:id])
    @task = Task.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.description %></td>
        <td><%= board.user_id %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @board.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @board.user_id %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Future Self</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"> -->

<link rel="stylesheet" href="https://bootflat.github.io/bootflat/css/bootflat.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>

<!--  -->
<%= yield %>


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <section class="hide">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :data_init %><br>
    <%= f.datetime_select :data_init %>
  </div>
  <div class="field">
    <%= f.label :date_end %><br>
    <%= f.datetime_select :date_end %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.text_field :board_id %>
  </div> 
  <div class="field">
    <%= f.label :dad %><br>
    <%= f.text_field :dad %>
  </div>
  </section>



</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
  
    <%= f.submit "Criar Tarefa", :class => "btn btn-primary" %>
  
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data init</th>
      <th>Date end</th>
      <th>Order</th>
      <th>Objetivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.data_init %></td>
        <td><%= task.date_end %></td>
        <td><%= task.order %></td>
        <td><%= task.board_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Data init:</strong>
  <%= @task.data_init %>
</p>

<p>
  <strong>Date end:</strong>
  <%= @task.date_end %>
</p>

<p>
  <strong>Order:</strong>
  <%= @task.order %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @task.objetivo_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Provider</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/editor.html.erb
<div class="container-fluid editor row no-gutters">
<<<<<<< HEAD
  <header class="cd-main-header">
    <nav class="cd-nav">
        <%= image_tag "logo/FutureSelf-normal _texto.png", :width => "140px", :class => "cd-logo"%>
      
    </nav>
  </header>
<main class="cd-main-content">
  <nav class="cd-side-nav">
      <ul>

          <li class="cd-label"><%= image_tag "logo/FutureSelf-normal _icon.png", :width => "140px"%>
          <%= image_tag "logo/FutureSelf-normal _texto.png", :width => "140px" %>
          </li>
          <li class="has-children overview">
              <%= link_to('Boards', root_path, :method => :delete) %>
          </li>
          <li class="notifications active">
              <%= link_to('Home', root_path, :method => :delete) %>
          </li>


          <!-- other list items here -->
          <li><%= link_to "Sign out", users_sign_out_path, :method => :delete %></li>
      </ul>

      <!-- other unordered lists here -->
  </nav>

  <div class="content-wrapper  main-editor">
    <header>
      <h2>
      <%if !@Task.nil? && !@Task.parent.nil? %>
        <%= link_to editor_task_path(@Task.parent.id) do %>
          <i style="font-size: 16px;  position: relative;top: -2px;left: -10px;" class="fa fa-chevron-left"></i>
        <% end %>
      <% end %>


      <a><%= @Task.title %></a>
      <a>
        <span class="header-sub">24h</span>
      </a>
      </h2>
      
<<<<<<< HEAD
      
        <% 
        s = []
        taskParent = @Task
        while !taskParent.parent.nil?
          s.push(link_to taskParent.parent.title, editor_task_path(taskParent.parent.id))
        
          taskParent = taskParent.parent
         end 
         %>

         <% if s.length != 0 %>

          <ol class="breadcrumb">

         <% while s.length != 0
          %>
          <li>
            <%= s.pop() %>
          </li>
         <% end %>
      </ol>
   <% end %>

    </header>
    <section>
      <div class="timeline-detail">
      <%

      if @Task.children.length != 0
        x = 12/@Task.children.length 
      else
        x = 12
      end

      for i in 0..@Task.children.length-1  %>

      <div class="col-sm-<%= x %> col-md-<%= x %> ">
        <i class="fa fa-check-circle checked">&nbsp;</i>
          <h3>
            <%= link_to taskParent.children[i].title, editor_task_path(taskParent.children[i].id) %>
          </h3>

          <ul class="item-tasks-list">
            <li><input type="text" id="nova" placeholder="Próximas Tarefas..."></input></li>            
            <li><a>Filho.Filho.Title</a></li>
            <li><a href="">Compose Database</a></li>
            <li><a href="">Image Reconizition</a></li>
            <li><a href="">Natural Language</a></li>            
          </ul>
        </div>
      <% end %>
      </div>

      <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Adicionar Tarefa
</button>
      </div>
    </section>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Adicionar Tarefa</h4>
      </div>
      <div class="modal-body">
        <%= render 'tasks/form' %>

      
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
</script>

app/views/welcome/index.html.erb
<br/><br/><br/><br/>
  <div class="wrapper">
    <%= image_tag "logo/FutureSelf-normal _logotipo.png", :width => "280px", :class => "cd-logo center-image"%>
    <br/><br/><br/><br/>
    <br/><br/><br/><br/>
    <br/>
    <p>Planeje a sua vida</p>
    <br/><br/><br/>
    <br/>
    <%= link_to "Entre com o Facebook", user_omniauth_authorize_path(:facebook), :class => "btn btn-lg btn-primary btn-block", :style => "color:#FFF;"  %>
  </div>


<style type="text/css">

body {
  background: url('<%= image_url "bg.jpg" %>');
  background-size: cover; 
}

p{
  font-size: 21px;
}

.wrapper {  
  text-align: center;

  background: #eee !important;  
  
  margin-top: 80px;
  margin-bottom: 80px;
  width: 50%;
  margin: 0 auto;
}

</style>